name = "tteut"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
ADMIN_EMAIL = "amansman77@gmail.com"
GOOGLE_REDIRECT_URI = "https://tteut.yetimates.com/auth/callback"
NEXT_PUBLIC_SITE_URL = "https://tteut.yetimates.com"

[[d1_databases]]
binding = "DB"
database_name = "shared-db"
database_id = "894124e2-8236-4647-a3a0-bc8674865889"
migrations_dir = "migrations"
